export let majors = [
    "Classical Civilization",
    "Classical Languages & Lit",
    "Classical Studies",
    "Communication",
    "Computer Engineering",
    "Computer Science",
    "Computer Sci & Linguistics",
    "Criminal Justice",
    "Criminology, Law, and Justice",
    "CUPPA-Undeclared",
    "Data Science",
    "Engineering Management",
    "Engineering Nondegree-CE",
    "Engineering Physics",
    "Engineering - Pre-CS & Design",
    "Engineering - Pre-Data Science",
    "Engineering-Undeclared",
    "English",
    "Entrepreneurship",
    "Estate Planning",
    "Human Development & Learning",
    "Jazz Studies",
    "Liberal Arts - Pre-CS & Ling",
    "Liberal Arts - Pre-IHS",
    "Liberal Arts - PreNeuroscience",
    "Liberal Arts - Undeclared",
    "Liberal Studies",
    "Management",
    "Management Science, General",
    "Marketing",
    "Math and Computer Science",
    "Math & Computer Science",
    "Nondegree-CE",
    "Nondegree Course-CE",
    "Nursing (BSN)",
    "Pharmacy (PharmD)",
    "Philosophy"
];

export let minors = [
    "African American Studies ",
    "Ancient Greek",
    "Anthropology",
    "Arabic",
    "Architectural Studies",
    "Communication",
    "Computer Engineering",
    "Computer Science",
    "Criminal Justice",
    "Criminology, Law, and Justice",
    "Disability & Human Development",
    "Earth & Environmental Sciences",
    "Economics",
    "Education",
    "Electrical Engineering",
    "English",
    "English as a Second Language",
    "Entrepreneurship",
    "Environmental Engineering",
    "Finance",
    "Food Science",
    "French",
    "French and Francophone Studies",
    "Gender and Women's Studies",
    "Geographic Info. Systems",
    "Geography",
    "German",
    "Germanic Studies",
    "Global Asian Studies",
    "History",
    "Labor Markets &Workforce Devel",
    "LAS International Studies",
    "Latin",
    "Latina/Latino Studies",
    "Latin Amer and Latino Studies",
    "Latin American Studies",
    "Law and Society",
    "Leadership",
    "Life Science Visualization",
    "Linguistics",
    "Math & Computer Science",
    "Mathematics",
    " "
];